name: Release Please

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      force_release:
        description: Force a release
        required: true
        type: boolean
      force_release_version:
        description: Version of the release
        required: false
        type: string

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created || github.event.inputs.force_release }}
    steps:
      - uses: actions/checkout@v4

      - uses: nekowinston/setup-deno@v1

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          registry-url: "https://registry.npmjs.org"

      - name: Build
        run: deno task build

      - name: Publish NPM package
        working-directory: dist/npm
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Upload the palette files
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tar czf catppuccin.tar.gz --directory=dist/palettes/ .
          pushd dist/palettes; zip -r "$GITHUB_WORKSPACE/catppuccin.zip" *; popd
          gh release upload ${{ needs.release-please.outputs.tag_name || inputs.force_release_version }} catppuccin.zip catppuccin.tar --clobber
